/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class Calc extends javax.swing.JFrame {
    char operator ;
        int number1=0;

    /**
     * Creates new form Calc
     */
    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        var_text = new javax.swing.JTextField();
        var_clear = new javax.swing.JButton();
        var_addition = new javax.swing.JButton();
        var2 = new javax.swing.JButton();
        var3 = new javax.swing.JButton();
        var4 = new javax.swing.JButton();
        var1 = new javax.swing.JButton();
        var6 = new javax.swing.JButton();
        var7 = new javax.swing.JButton();
        var8 = new javax.swing.JButton();
        var9 = new javax.swing.JButton();
        var0 = new javax.swing.JButton();
        var_equal = new javax.swing.JButton();
        var5 = new javax.swing.JButton();
        var_substraction = new javax.swing.JButton();
        var_division = new javax.swing.JButton();
        var_multiplication = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Calculator"));

        var_text.setEditable(false);
        var_text.setBackground(new java.awt.Color(255, 255, 255));

        var_clear.setText("CE");
        var_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var_clearActionPerformed(evt);
            }
        });

        var_addition.setText("+");
        var_addition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var_additionActionPerformed(evt);
            }
        });

        var2.setText("2");
        var2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var2ActionPerformed(evt);
            }
        });

        var3.setText("3");
        var3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var3ActionPerformed(evt);
            }
        });

        var4.setText("4");
        var4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var4ActionPerformed(evt);
            }
        });

        var1.setText("1");
        var1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var1ActionPerformed(evt);
            }
        });

        var6.setText("6");
        var6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var6ActionPerformed(evt);
            }
        });

        var7.setText("7");
        var7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var7ActionPerformed(evt);
            }
        });

        var8.setText("8");
        var8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var8ActionPerformed(evt);
            }
        });

        var9.setText("9");
        var9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var9ActionPerformed(evt);
            }
        });

        var0.setText("0");
        var0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var0ActionPerformed(evt);
            }
        });

        var_equal.setText("=");
        var_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var_equalActionPerformed(evt);
            }
        });

        var5.setText("5");
        var5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var5ActionPerformed(evt);
            }
        });

        var_substraction.setText("-");
        var_substraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var_substractionActionPerformed(evt);
            }
        });

        var_division.setText("/");
        var_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var_divisionActionPerformed(evt);
            }
        });

        var_multiplication.setText("X");
        var_multiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var_multiplicationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(var4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(var7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(var8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(var5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(var0, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(var6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(var9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(var_division, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(var_substraction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(var_multiplication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(var_equal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(var1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(var2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(var3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(var_addition, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(var_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(var_text)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(var_text, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(var2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(var3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(var1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(var_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(var6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(var5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(var4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(var9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(var8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(var7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(var_addition)
                        .addGap(12, 12, 12)
                        .addComponent(var_substraction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(var_division)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(var_multiplication)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(var_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(var0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void var1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var1ActionPerformed
        // TODO add your handling code here:
      //  var_text.setText("1");
      if(var_text.getText().equals(0)||var_text.getText().equals("")){
          var_text.setText("1");
      }else{
                  var_text.setText(var_text.getText() + "1");
                  }
      
      
    }//GEN-LAST:event_var1ActionPerformed

    private void var2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var2ActionPerformed
        // TODO add your handling code here:
       if(var_text.getText().equals(0)||var_text.getText().equals("")){
          var_text.setText("2");
      }else{
                  var_text.setText(var_text.getText() + "2");
                  }
    }//GEN-LAST:event_var2ActionPerformed

    private void var3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var3ActionPerformed
        // TODO add your handling code here:
        if(var_text.getText().equals(0)||var_text.getText().equals("")){
          var_text.setText("3");
      }else{
                  var_text.setText(var_text.getText() + "3");
                  }
    }//GEN-LAST:event_var3ActionPerformed

    private void var4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var4ActionPerformed
        // TODO add your handling code here:
       if(var_text.getText().equals(0)||var_text.getText().equals("")){
          var_text.setText("4");
      }else{
                  var_text.setText(var_text.getText() + "4");
                  }
    }//GEN-LAST:event_var4ActionPerformed

    private void var5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var5ActionPerformed
        // TODO add your handling code here:
        if(var_text.getText().equals(0)||var_text.getText().equals("")){
          var_text.setText("4");
      }else{
                  var_text.setText(var_text.getText() + "4");
                  }
    }//GEN-LAST:event_var5ActionPerformed

    private void var6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var6ActionPerformed
        // TODO add your handling code here:
        if(var_text.getText().equals(0)||var_text.getText().equals("")){
          var_text.setText("6");
      }else{
                  var_text.setText(var_text.getText() + "6");
                  }
    }//GEN-LAST:event_var6ActionPerformed

    private void var7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var7ActionPerformed
        // TODO add your handling code here:
       if(var_text.getText().equals(0)||var_text.getText().equals("")){
          var_text.setText("7");
      }else{
                  var_text.setText(var_text.getText() + "7");
                  }
    }//GEN-LAST:event_var7ActionPerformed

    private void var8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var8ActionPerformed
        // TODO add your handling code here:
        if(var_text.getText().equals(0)||var_text.getText().equals("")){
          var_text.setText("8");
      }else{
                  var_text.setText(var_text.getText() + "8");
                  }
    }//GEN-LAST:event_var8ActionPerformed

    private void var9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var9ActionPerformed
        // TODO add your handling code here:
        if(var_text.getText().equals(0)||var_text.getText().equals("")){
          var_text.setText("9");
      }else{
                  var_text.setText(var_text.getText() + "9");
                  }
    }//GEN-LAST:event_var9ActionPerformed

    private void var0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var0ActionPerformed
        // TODO add your handling code here:
        if(var_text.getText().equals(0)||var_text.getText().equals("")){
          var_text.setText("0");
      }else{
                  var_text.setText(var_text.getText() + "0");
                  }
    }//GEN-LAST:event_var0ActionPerformed

    private void var_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var_clearActionPerformed
        // TODO add your handling code here:
        var_text.setText("");
    }//GEN-LAST:event_var_clearActionPerformed

    private void var_additionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var_additionActionPerformed
        // TODO add your handling code here:
        operator = '+';
        number1 = Integer.parseInt(var_text.getText());
        var_text.setText(null);
    }//GEN-LAST:event_var_additionActionPerformed

    private void var_substractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var_substractionActionPerformed
        // TODO add your handling code here:
         operator = '-';
        number1 = Integer.parseInt(var_text.getText());
        var_text.setText(null);
    }//GEN-LAST:event_var_substractionActionPerformed

    private void var_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var_divisionActionPerformed
        // TODO add your handling code here:
         operator = '/';
        number1 = Integer.parseInt(var_text.getText());
        var_text.setText(null);
    }//GEN-LAST:event_var_divisionActionPerformed

    private void var_multiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var_multiplicationActionPerformed
        // TODO add your handling code here:
         operator = 'X';
        number1 = Integer.parseInt(var_text.getText());
        var_text.setText(null);
    }//GEN-LAST:event_var_multiplicationActionPerformed

    private void var_equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var_equalActionPerformed
        // TODO add your handling code here:
        int number2 = 0, sum =0;
        String str;
         
        switch (operator)
        {
            case '+':
                number2 = Integer.parseInt(var_text.getText());
                sum = number1 + number2;
                str = Integer.toString(sum);
                var_text.setText(str);
                break;
                case '-':
                number2 = Integer.parseInt(var_text.getText());
                sum = number1 - number2;
                str = Integer.toString(sum);
                var_text.setText(str);
                break;
                case '/':
                number2 = Integer.parseInt(var_text.getText());
                sum = number1 / number2;
                str = Integer.toString(sum);
                var_text.setText(str);
                break;
                case 'X':
                number2 = Integer.parseInt(var_text.getText());
                sum = number1 * number2;
                str = Integer.toString(sum);
                var_text.setText(str);
                break;
        }
        
    }//GEN-LAST:event_var_equalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton var0;
    private javax.swing.JButton var1;
    private javax.swing.JButton var2;
    private javax.swing.JButton var3;
    private javax.swing.JButton var4;
    private javax.swing.JButton var5;
    private javax.swing.JButton var6;
    private javax.swing.JButton var7;
    private javax.swing.JButton var8;
    private javax.swing.JButton var9;
    private javax.swing.JButton var_addition;
    private javax.swing.JButton var_clear;
    private javax.swing.JButton var_division;
    private javax.swing.JButton var_equal;
    private javax.swing.JButton var_multiplication;
    private javax.swing.JButton var_substraction;
    private javax.swing.JTextField var_text;
    // End of variables declaration//GEN-END:variables
}
